### ISSUE TITLE
Tooltips instead of HTML output

### ISSUE THREAD

**Issue by sgarbesi** [natesilva/javascript-eslint.tmbundle#1]
The HTML output is nice looking, but hurts productivity. Every time you save a file, the HTML window pops up and the code window/frame loses focus forcing you to click the code window/frame again before you can update your code.

I forked and updated the library to throw the ESLint results into a tooltip. The change I made is a hack to let this happen, but I'm sure it should be in it's own function with a newly defined preference if you wanted to incorporate this functionality into the bundle.

Check it out here:
https://github.com/sgarbesi/javascript-eslint.tmbundle/compare/natesilva:master...master

Nice library by the way, very useful!

**Comment by natesilva** [comment]
I’ll look into this now that I’m working on this code again. It would be an option as I prefer the full window, but I can understand wanting a tooltip instead.

**Comment by koenpunt** [comment]
Instead of changing the output we should change how the output is updated. So instead of running eslint on save, we could make the output autorefresh.

I created a separate issue for this: #9

**Comment by koenpunt** [comment]
And a solution in #10

**Comment by natesilva** [comment]
Autorefresh, as well as displaying problems as clickable gutter icons with tooltip-like popups is all in version 3.0.0.
