### ISSUE TITLE
Can't see any feedback from ESLint

### ISSUE THREAD

**Issue by Bodacious** [natesilva/javascript-eslint.tmbundle#13]
I've installed this Bundle in TextMate 2 (v2.0-rc.4). I can see the JavaScript ESLint bundle listed in my bundles. 

But when I write some invalid javascript code, I don't see any feedback in the gutter. When I manually validate the JS with ctrl + shift + "V" it comes back as valid.

Any ideas?

<img width="1439" alt="screenshot 2017-04-08 12 27 31" src="https://cloud.githubusercontent.com/assets/73998/24828522/07efffca-1c57-11e7-99de-2a96f22bd7e6.png">

**Comment by Bodacious** [comment]
My bad. RTFM

**Comment by Yayuro** [comment]
Quick question .. how it's possible that you have eslint window integral part of an editor, not a popup ?

**Comment by natesilva** [comment]
It calls the `mate` command with the `--set-mark` and `--line` arguments. See `mate --help` in the Terminal for details.
