### ISSUE TITLE
Spurious .eslintignore warnings

### ISSUE THREAD

**Issue by acdha** [natesilva/javascript-eslint.tmbundle#5]
Validation always displays this message:

```
⚠ at line 0 position 1:  File ignored because of your .eslintignore file. Use --no-ignore to override.
```

There is no .eslintignore file in my project (or at any level of the parent directory hierarchy).

This does not appear to prevent actual errors from being reported – this will always be displayed at the bottom of the list.

**Comment by natesilva** [comment]
Thank you. This is fixed in v2.0.0.
