### ISSUE TITLE
Enable autoRefresh for preview

### ISSUE THREAD

**Issue by koenpunt** [natesilva/javascript-eslint.tmbundle#9]
Instead of running lint on save, we could autorefresh the preview by adding an `autoRefresh` property to the command's plist. Just like in the markdown bundle:

https://github.com/textmate/markdown.tmbundle/blob/82f2ffb82db588a94ddbc6b8fad4f895a81f7827/Commands/Markdown%20preview.plist#L5-L8

    <key>autoRefresh</key>
    <array>
    	<string>DocumentSaved</string>
    </array>

**Comment by natesilva** [comment]
This is working in version 3.0.0.
